import { z } from 'zod';
import { LIMITS } from './limits';
import { LENSES } from './lenses';
import { CLAUSE_CATEGORIES, RISK_LEVELS } from './types';

/**
 * Zod schemas for everything that crosses a trust boundary.
 *
 * Two boundaries matter here and they are validated with the same rigour:
 * 1. Browser -> server. The browser is not trusted, so every limit in `shared/limits.ts` is
 *    re-checked here even though the UI already enforced it. Unknown keys are stripped
 *    (`z.object`, not `z.strictObject`) so a future client field cannot break an older server.
 * 2. Model -> server. Gemini output is parsed before anything looks at it, so a malformed or
 *    manipulated response fails as a validation error instead of flowing into the UI.
 */

export const languageSchema = z.enum(['en', 'hi']);
export type Language = z.infer<typeof languageSchema>;

export const readingLevelSchema = z.enum(['simple', 'standard']);
export type ReadingLevel = z.infer<typeof readingLevelSchema>;

export const lensSchema = z.enum(LENSES);

export const clauseCategorySchema = z.enum(CLAUSE_CATEGORIES);

export const riskLevelSchema = z.enum(RISK_LEVELS);

/** Ids are generated by our own segmenter, so the format is strict on purpose. */
export const clauseIdSchema = z.string().regex(/^c\d{3,5}$/, 'Clause ids look like "c001"');

export const clauseSchema = z.object({
  id: clauseIdSchema,
  label: z.string().max(40).nullable(),
  heading: z.string().max(200).nullable(),
  text: z.string().min(1).max(LIMITS.maxClauseChars),
  page: z.number().int().positive().max(LIMITS.maxPages).nullable(),
  pageEnd: z.number().int().positive().max(LIMITS.maxPages).nullable(),
  // `order` is 0-based, so the highest legitimate value in a document of `maxClauses` is one less.
  order: z
    .number()
    .int()
    .nonnegative()
    .max(LIMITS.maxClauses - 1),
});

/**
 * A whole document's clauses.
 *
 * The total-character check is the one that actually protects cost and latency: 400 short
 * clauses and 40 long ones are very different prompts.
 */
export const clauseListSchema = z
  .array(clauseSchema)
  .min(1, 'The document has no readable clauses')
  .max(LIMITS.maxClauses)
  .superRefine((clauses, ctx) => {
    const total = clauses.reduce((sum, clause) => sum + clause.text.length, 0);
    if (total > LIMITS.maxTotalChars) {
      ctx.addIssue({
        code: 'custom',
        message: `Document text is ${total} characters; the limit is ${LIMITS.maxTotalChars}`,
      });
    }
    const ids = new Set<string>();
    for (const clause of clauses) {
      if (ids.has(clause.id)) {
        ctx.addIssue({ code: 'custom', message: `Duplicate clause id ${clause.id}` });
        return;
      }
      ids.add(clause.id);
    }
  });

const sharedRequestFields = {
  clauses: clauseListSchema,
  language: languageSchema,
  readingLevel: readingLevelSchema,
};

export const analyzeRequestSchema = z.object({
  ...sharedRequestFields,
  lenses: z.array(lensSchema).max(LENSES.length),
});

export const askRequestSchema = z.object({
  ...sharedRequestFields,
  question: z.string().trim().min(3).max(LIMITS.maxQuestionChars),
  history: z
    .array(
      z.object({
        question: z.string().max(LIMITS.maxQuestionChars),
        answer: z.string().max(4_000),
      }),
    )
    .max(LIMITS.maxHistoryTurns)
    .optional(),
});

/**
 * Compare carries two documents, so the character budget is checked across both.
 *
 * Without this, `clauseListSchema` would allow `maxTotalChars` on each side and a single
 * request could legitimately carry twice the intended payload.
 */
export const compareRequestSchema = z
  .object({
    clausesA: clauseListSchema,
    clausesB: clauseListSchema,
    language: languageSchema,
    readingLevel: readingLevelSchema,
  })
  .superRefine((request, ctx) => {
    const total = [...request.clausesA, ...request.clausesB].reduce(
      (sum, clause) => sum + clause.text.length,
      0,
    );
    if (total > LIMITS.maxTotalChars) {
      ctx.addIssue({
        code: 'custom',
        message: `Both documents together are ${total} characters; the limit is ${LIMITS.maxTotalChars}`,
      });
    }
  });

export const prepareRequestSchema = z.object({
  ...sharedRequestFields,
  lenses: z.array(lensSchema).max(LENSES.length),
  findings: z
    .array(
      z.object({
        clauseId: clauseIdSchema,
        category: clauseCategorySchema,
        risk: riskLevelSchema,
        title: z.string().max(200),
      }),
    )
    .max(LIMITS.maxClauses),
  unansweredQuestions: z.array(z.string().max(LIMITS.maxQuestionChars)).max(20),
});

export const sessionRequestSchema = z.object({
  turnstileToken: z.string().min(1).max(2_048),
});

/* ------------------------------------------------------------------ *
 * Model output. Deliberately permissive about length and strict about
 * shape: a long explanation is fine, a missing clause id is not.
 * ------------------------------------------------------------------ */

/** The model returns a clause id and a quote; page numbers always come from our own data. */
const modelCitationSchema = z.object({
  clauseId: z.string().max(16),
  quote: z.string().max(LIMITS.maxQuoteChars),
});

export const analyzeModelOutputSchema = z.object({
  documentSummary: z.object({
    documentType: z.string().max(200).nullish(),
    employer: z.string().max(200).nullish(),
    role: z.string().max(200).nullish(),
    startDate: z.string().max(100).nullish(),
    noticePeriod: z.string().max(200).nullish(),
    probation: z.string().max(200).nullish(),
    bondOrPenalty: z.string().max(400).nullish(),
    overview: z.string().max(2_000),
    sourceClauseIds: z.array(z.string().max(16)).max(LIMITS.maxClauses).default([]),
  }),
  findings: z
    .array(
      z.object({
        clauseId: z.string().max(16),
        category: clauseCategorySchema,
        risk: riskLevelSchema,
        title: z.string().max(200),
        explanation: z.string().max(2_000),
        whyItMatters: z.string().max(2_000),
        quote: z.string().max(LIMITS.maxQuoteChars),
        questionsToAsk: z.array(z.string().max(400)).max(5).default([]),
        confidence: z.enum(['high', 'medium', 'low']),
      }),
    )
    .max(LIMITS.maxClauses),
});

export const askModelOutputSchema = z.object({
  status: z.enum(['answered', 'not_in_document', 'needs_professional']),
  answer: z.string().max(4_000),
  citations: z.array(modelCitationSchema).max(8).default([]),
  missingInfo: z.array(z.string().max(400)).max(8).default([]),
  suggestedQuestions: z.array(z.string().max(400)).max(5).default([]),
});

export const compareModelOutputSchema = z.object({
  changes: z
    .array(
      z.object({
        pairId: z.string().max(32),
        changeType: z.enum(['ADDED', 'REMOVED', 'CHANGED']),
        impact: z.enum(['BETTER_FOR_EMPLOYEE', 'WORSE_FOR_EMPLOYEE', 'NEUTRAL', 'UNCLEAR']),
        summary: z.string().max(1_000),
        quoteA: z.string().max(LIMITS.maxQuoteChars).nullish(),
        quoteB: z.string().max(LIMITS.maxQuoteChars).nullish(),
      }),
    )
    .max(200),
});

export const prepareModelOutputSchema = z.object({
  checklistBeforeSigning: z.array(z.string().max(400)).max(20).default([]),
  questionsForHR: z.array(z.string().max(400)).max(20).default([]),
  questionsForLawyer: z.array(z.string().max(400)).max(20).default([]),
  missingInformation: z.array(z.string().max(400)).max(20).default([]),
  documentsToBring: z.array(z.string().max(400)).max(20).default([]),
});

/* ------------------------------------------------------------------ *
 * Server responses. The client re-validates these so a proxy or a
 * cached older deployment cannot feed the UI a shape it cannot render.
 * ------------------------------------------------------------------ */

export const verificationStatusSchema = z.enum(['verified', 'fuzzy', 'unverified']);

/**
 * `exactOptional` rather than `optional`: with `exactOptionalPropertyTypes` on, an offset is
 * either absent or a number, never explicitly `undefined`. Plain `.optional()` would infer
 * `start?: number | undefined`, which does not match the `VerifiedQuote` the UI consumes.
 */
export const verifiedQuoteSchema = z.object({
  clauseId: z.string(),
  quote: z.string(),
  status: verificationStatusSchema,
  start: z.exactOptional(z.number().int().nonnegative()),
  end: z.exactOptional(z.number().int().nonnegative()),
});

export const ruleHitSchema = z.object({
  ruleId: z.string(),
  clauseId: z.string(),
  severity: riskLevelSchema,
  title: z.string(),
  message: z.string(),
  basis: z.string(),
  questions: z.array(z.string()),
  lastReviewed: z.string(),
  details: z.exactOptional(z.record(z.string(), z.string())),
});

export const analyzeResponseSchema = z.object({
  documentSummary: z.object({
    documentType: z.string().nullable(),
    employer: z.string().nullable(),
    role: z.string().nullable(),
    startDate: z.string().nullable(),
    noticePeriod: z.string().nullable(),
    probation: z.string().nullable(),
    bondOrPenalty: z.string().nullable(),
    overview: z.string(),
    sourceClauseIds: z.array(z.string()),
  }),
  findings: z.array(
    z.object({
      clauseId: z.string(),
      category: clauseCategorySchema,
      risk: riskLevelSchema,
      title: z.string(),
      explanation: z.string(),
      whyItMatters: z.string(),
      evidence: verifiedQuoteSchema,
      questionsToAsk: z.array(z.string()),
      modelConfidence: z.enum(['high', 'medium', 'low']),
    }),
  ),
  ruleHits: z.array(ruleHitSchema),
  missingInfo: z.array(z.object({ ruleId: z.string(), label: z.string(), question: z.string() })),
  stats: z.object({
    verified: z.number().int().nonnegative(),
    fuzzy: z.number().int().nonnegative(),
    unverified: z.number().int().nonnegative(),
  }),
  // Defaulted so a response from a deployment that predates the field still renders.
  partial: z.boolean().default(false),
});

export const askResponseSchema = z.object({
  status: z.enum(['answered', 'not_in_document', 'needs_professional']),
  answer: z.string(),
  citations: z.array(verifiedQuoteSchema),
  missingInfo: z.array(z.string()),
  suggestedQuestions: z.array(z.string()),
});

export const compareResponseSchema = z.object({
  changes: z.array(
    z.object({
      pairId: z.string(),
      changeType: z.enum(['ADDED', 'REMOVED', 'CHANGED']),
      impact: z.enum(['BETTER_FOR_EMPLOYEE', 'WORSE_FOR_EMPLOYEE', 'NEUTRAL', 'UNCLEAR']),
      summary: z.string(),
      category: clauseCategorySchema,
      quoteA: verifiedQuoteSchema.nullable(),
      quoteB: verifiedQuoteSchema.nullable(),
    }),
  ),
  unchangedCount: z.number().int().nonnegative(),
});

export const prepareResponseSchema = z.object({
  checklistBeforeSigning: z.array(z.string()),
  questionsForHR: z.array(z.string()),
  questionsForLawyer: z.array(z.string()),
  missingInformation: z.array(z.string()),
  documentsToBring: z.array(z.string()),
});

export const sessionResponseSchema = z.object({
  token: z.string(),
  expiresAt: z.number().int().positive(),
});

export const apiErrorSchema = z.object({
  error: z.object({
    code: z.enum([
      'INVALID_INPUT',
      'TOO_LARGE',
      'RATE_LIMITED',
      'UNAUTHORIZED',
      'MODEL_BLOCKED',
      'MODEL_INVALID_OUTPUT',
      'UPSTREAM_TIMEOUT',
      'INTERNAL',
    ]),
    message: z.string(),
    retryable: z.boolean(),
  }),
});
